import 'package:get/get.dart';
import 'package:get_storage/get_storage.dart';

const Map<String, String> _deCatalog = {
  'Fresh Categories': 'Frische Kategorien',
  'Good Morning': 'Guten Morgen',
  'Good Afternoon': 'Guten Tag',
  'Good Evening': 'Guten Abend',
  'What are you craving today?': 'Worauf haben Sie heute Lust?',
  'Search shakes, drinks and more...': 'Shakes, Getränke und mehr suchen...',
  'Explore Our Menu': 'Entdecken Sie unser Menü',
  "Today's Special": 'Heutiges Spezial',
  'Try Now': 'Jetzt probieren',
  'Popular Right Now': 'Derzeit beliebt',
  'New Arrivals': 'Neu eingetroffen',
  'Fresh Juices': 'Frische Säfte',
  'Made with\nReal Fruits': 'Mit echten\nFrüchten',
  'No artificial flavors': 'Keine künstlichen Aromen',
  'Premium\nIngredients': 'Premium-\nZutaten',
  'Fresh & high quality': 'Frisch & hochwertig',
  'Crafted with\nLove': 'Mit Liebe\ngemacht',
  'For your cravings': 'Für Ihren Appetit',
  'Good drinks. Great moments.': 'Gute Getränke. Tolle Momente.',
  'Wallet Balance': 'Guthaben',
  'Guest': 'Gast',
  'Account': 'Konto',
  'DRINK': 'GETRÄNK',
  'GOOD IN EVERY SIP': 'GUT IN JEDEM SCHLUCK',
  'Natural\nIngredients': 'Natürliche\nZutaten',
  'Served\nHot': 'Heiß\nserviert',
  'Served\nChilled': 'Gekühlt\nserviert',
  'Hygienically\nPrepared': 'Hygienisch\nzubereitet',
  'Caution': 'Hinweis',
  'Add a note (optional)': 'Notiz hinzufügen (optional)',
  'Add note (extra mayo, cheese, etc.)':
      'Notiz hinzufügen (extra Mayo, Käse usw.)',
  'Select Options': 'Optionen auswählen',
  'Search': 'Suchen',
  'Size': 'Größe',
  'Calories': 'Kalorien',
  'Small': 'Klein',
  'Medium': 'Mittel',
  'Large': 'Groß',
  'Regular': 'Normal',
  'Chocolate Shakes': 'Schokoladen-Shakes',
  'Coffee': 'Kaffee',
  'Fruit Shots': 'Fruchtshots',
  'Hot Drinks': 'Heiße Getränke',
  'Iced Tea': 'Eistee',
  'Juices': 'Säfte',
  'Milkshakes': 'Milchshakes',
  'Mocktails': 'Mocktails',
  'Mojitos': 'Mojitos',
  'Zesty Lemon Iced Tea': 'Spritziger Zitronen-Eistee',
  'Peach Breeze Iced Tea': 'Pfirsichbrise-Eistee',
  'Iced Coffee Classic': 'Klassischer Eiskaffee',
  'Mocha Iced Coffee': 'Mokka-Eiskaffee',
  'Caramel Latte Iced Coffee': 'Karamell-Latte-Eiskaffee',
  'Masala Tea': 'Masala-Tee',
  'Green Tea': 'Grüner Tee',
  'Lychee Shot': 'Litschi-Shot',
  'Guava Regular Shot': 'Guave Regular Shot',
  'Guava Spicy Shot': 'Scharfer Guave-Shot',
  'Jamun Shot': 'Jamun-Shot',
  'Jamun-Shot': 'Jamun-Shot',
  'Strawberry Shot': 'Erdbeer-Shot',
  'Strawberry-Shot': 'Erdbeer-Shot',
  'Erdbeer-Shot': 'Erdbeer-Shot',
  'Kiwi Shot': 'Kiwi-Shot',
  'Paan Shot': 'Paan-Shot',
  'Falsa Shot': 'Falsa-Shot',
  'Classic Mint Mojito': 'Klassischer Minz-Mojito',
  'Watermelon Mojito': 'Wassermelonen-Mojito',
  'Green Apple Mojito': 'Grüner-Apfel-Mojito',
  'Strawberry Mojito': 'Erdbeer-Mojito',
  'Tangy Mango Mojito': 'Spritziger Mango-Mojito',
  'Spiced Mint Mojito': 'Gewürzter Minz-Mojito',
  'Mango Juice': 'Mango-Saft',
  'Masala Citrus Rush': 'Masala-Zitrus-Rush',
  'Classic Lemon Fusion': 'Klassische Zitronen-Fusion',
  'Strawberry Bliss Shake': 'Erdbeer-Bliss-Shake',
  'Golden Mango Bliss Shake': 'Goldener Mango-Bliss-Shake',
  'KitKat Milkshake': 'KitKat-Milchshake',
  'Nutella Milkshake': 'Nutella-Milchshake',
  'Chocolate Brownie Milkshake': 'Schokoladen-Brownie-Milchshake',
  'Hot Latte Coffee': 'Heißer Latte-Kaffee',
  'Refreshing lemon iced tea.': 'Erfrischender Zitronen-Eistee.',
  'Smooth peach iced tea.': 'Sanfter Pfirsich-Eistee.',
  'Classic chilled coffee.': 'Klassischer gekühlter Kaffee.',
  'Coffee with chocolate blend.': 'Kaffee mit Schokoladenmischung.',
  'Caramel flavored iced coffee.': 'Eiskaffee mit Karamellgeschmack.',
  'Indian spiced tea.': 'Indisch gewürzter Tee.',
  'Light healthy tea.': 'Leichter gesunder Tee.',
  'Sweet tropical lychee shot.': 'Süßer tropischer Litschi-Shot.',
  'Fresh guava flavor shot.': 'Frischer Guave-Shot.',
  'Spicy tangy guava shot.': 'Scharfer, spritziger Guave-Shot.',
  'Rich jamun fruity shot.': 'Fruchtiger Jamun-Shot.',
  'Fruchtiger Jamun-Shot.': 'Fruchtiger Jamun-Shot.',
  'Fresh strawberry shot.': 'Frischer Erdbeer-Shot.',
  'Tangy kiwi shot.': 'Spritziger Kiwi-Shot.',
  'Refreshing paan flavored shot.': 'Erfrischender Paan-Shot.',
  'Classic falsa tangy shot.': 'Klassischer spritziger Falsa-Shot.',
  'Refreshing mint mojito.': 'Erfrischender Minz-Mojito.',
  'Cool watermelon mojito.': 'Kühler Wassermelonen-Mojito.',
  'Tangy apple mojito.': 'Spritziger Apfel-Mojito.',
  'Sweet strawberry mojito.': 'Süßer Erdbeer-Mojito.',
  'Mango citrus mojito.': 'Mango-Zitrus-Mojito.',
  'Mint mojito with spice.': 'Minz-Mojito mit Gewürzen.',
  'Fresh mango juice.': 'Frischer Mango-Saft.',
  'Spicy citrus drink.': 'Würziges Zitrusgetränk.',
  'Traditional shikanji.': 'Traditioneller Shikanji.',
  'Creamy strawberry shake.': 'Cremiger Erdbeer-Shake.',
  'Rich mango shake.': 'Reichhaltiger Mango-Shake.',
  'Chocolate with KitKat crunch.': 'Schokolade mit KitKat-Crunch.',
  'Rich Nutella shake.': 'Reichhaltiger Nutella-Shake.',
  'Brownie blended shake.': 'Brownie-Mix-Shake.',
  'Smooth hot latte.': 'Sanfter heißer Latte.',
  'Privacy Policy': 'Datenschutzerklärung',
  'User Policy': 'Nutzerrichtlinie',
  'Refund Policy': 'Rückerstattungsrichtlinie',
  'Delete Account': 'Konto löschen',
  'Terms And Conditions': 'Allgemeine Geschäftsbedingungen',
};

bool get isGermanSelected {
  final stored = GetStorage().read('languageCode')?.toString();
  return stored == 'de' || Get.locale?.languageCode == 'de';
}

String localizeText(String? value) {
  if (value == null || value.isEmpty || !isGermanSelected) return value ?? '';
  return _deCatalog[value] ?? _deCatalog[value.trim()] ?? value;
}
