Map<String, String> germany = {
  'WELCOME_BACK': 'Willkommen zurück',
  'HOME': 'Startseite',
  'HISTORY': 'Verlauf',
  'PROFILE': 'Profil',
  'COMPLETE_DELIVERY': 'Lieferung abschließen',
  'RETURN_DELIVERY': 'Lieferung zurückgeben',
  'ACTIVE_ORDERS': 'Aktive Bestellungen',
  'SEE_DETAILS': 'Details ansehen',
  'GET_DIRECTION': 'Route anzeigen',
  'ORDER_ID': 'Bestell-ID: ',
  'SEE_ORDER_DETAILS': 'Bestelldetails ansehen',
  'CONFIRM_DELIVERY': 'Lieferung bestätigen',
  'CUSTOMER': 'Kunde',
  'ORDER_DETAILS': 'Bestelldetails',
  'YOUR_ESTIMATE_DELIVERY_TIME': 'Ihre geschätzte Lieferzeit',
  'PAYMENT_INFO': 'Zahlungsinformationen',
  'METHOD': 'Methode',
  'STATUS': 'Status',
  'ORDER_SUMMERY': 'Bestellübersicht',
  'EXTRAS': 'Extras',
  'INSTRUCTIONS': 'Anweisungen: ',
  'SUBTOTAL': 'Zwischensumme',
  'DISCOUNT': 'Rabatt',
  'DELIVERY_CHARGE': 'Liefergebühr',
  'TOTAL': 'Gesamt',
  'CONFIRM_DELIVERY_ALERT':
      'Sind Sie sicher, dass Sie die Lieferung bestätigen möchten?',
  'NO_CANCEL': 'Nein, abbrechen',
  'YES_CONFIRM': 'Ja, bestätigen',
  'YES_COLLECT': 'Ja, einsammeln',
  'CASH_ON_DELIVERY': 'Barzahlung bei Lieferung',
  'ORDER_SUCCESSFULLY_DELIVERED': 'Bestellung erfolgreich geliefert',
  'BACK_TO_HOME': 'Zurück zur Startseite',
  'OPEN': 'Offen',
  'MY_PROFILE': 'Mein Profil',
  'BRANCH': 'Filiale',
  'LOG_OUT': 'Abmelden',
  'ERROR': 'Fehler',
  'SUCCESS': 'Erfolg',
  'CHANGE_PASSWORD': 'Passwort ändern',
  'CHANGE_LANGUAGE': 'Sprache ändern',
  'TERMS_CONDITION': 'Allgemeine Geschäftsbedingungen',
  'PRIVACY_POLICY': 'Datenschutzrichtlinie',
  'EDIT_PROFILE': 'Profil bearbeiten',
  'FIRST_NAME': 'Vorname',
  'LAST_NAME': 'Nachname',
  'EMAIL': 'E-Mail',
  'PASSWORD': 'Passwort',
  'MOBILE_NUMBER': 'Handynummer',
  'UPDATE_PROFILE': 'Profil aktualisieren',
  'OLD_PASSWORD': 'Altes Passwort',
  'NEW_PASSWORD': 'Neues Passwort',
  'RETYPE_NEW_PASSWORD': 'Neues Passwort erneut eingeben',
  'DELETE_ACCOUNT': 'Konto löschen',
  'PROFILE_UPDATE': 'Profil aktualisiert',
  'PROFILE_UPDATE_SUCCESSFULLY': 'Profil erfolgreich aktualisiert',
  'PASSWORD_UPDATE_SUCCESSFULLY': 'Passwort erfolgreich aktualisiert',
  'CONFIRM_NEW_PASSWORD': 'Neues Passwort bestätigen',
  'PLEASE_ENTER_VALID_INPUT': 'Bitte geben Sie gültige Daten ein',
  'PRESS_BACK_AGAIN_TO_EXIT': 'Drücken Sie erneut Zurück, um zu beenden.',
  'REMEMBER_ME': 'Angemeldet bleiben',
  'ORDER_HISTORY': 'Bestellverlauf',
  'IMAGE_SHOULD_BE_LESS_THAN_2MB': 'Das Bild sollte kleiner als 2 MB sein',
  'PROFILE_IMAGE_SAVED_SUCCESSFULLY': 'Profilbild erfolgreich gespeichert',
  'SOMETHING_WRONG': 'Etwas ist schiefgelaufen',
  'YOU_HAVE_NO_ORDER_FOR_DELIVERY': 'Sie haben keine Bestellung zur Lieferung',
  'WAIT_NOTE':
      'Warten Sie, bis Ihr Filialleiter Ihnen die Bestellung zur Lieferung zuweist.',
  'YOU_HAVE_NO_ORDER_HISTORY': 'Sie haben keinen Bestellverlauf',
  'ALL_BRANCH': 'Alle Filialen',
  'INSTRUCTION': 'Anweisung',
  'DELIVERY_ADDRESS': 'Lieferadresse',
  'PAID': 'Bezahlt',
  'UNPAID': 'Unbezahlt',
  'PICK_PAY': 'Abholen & Bezahlen',
  'DO_YOU_COLLECT_PAYMENT': 'Nehmen Sie die Zahlung entgegen?',
  'AMOUNT': 'Betrag',
  'PLEASE_TYPE_FIRST_NAME': 'Bitte geben Sie Ihren Vornamen ein',
  'PLEASE_TYPE_LAST_NAME': 'Bitte geben Sie Ihren Nachnamen ein',
  'PLEASE_TYPE_EMAIL': 'Bitte geben Sie Ihre E-Mail-Adresse ein',
  'PLEASE_TYPE_OLD_PASSWORD': 'Bitte geben Sie Ihr altes Passwort ein',
  'PLEASE_TYPE_NEW_PASSWORD': 'Bitte geben Sie Ihr neues Passwort ein',
  'PLEASE_RETYPE_PASSWORD': 'Bitte geben Sie das Passwort erneut ein',
  'PASSWORD_MUST_BE_SIX': 'Das Passwort muss mindestens 6 Zeichen lang sein',
  'ENTER_VALID_EMAIL': 'Geben Sie eine gültige E-Mail-Adresse ein',
  'PLEASE_TYPE_PASSWORD': 'Bitte geben Sie Ihr Passwort ein',
  'LOCATION_SERVICE_DENIED': 'Der Standortdienst wurde verweigert!',
  'LOCATION_PERMISSION_NOT_ENABLED':
      'Die Standortberechtigung ist nicht aktiviert!',
  'PICK_AND_PAY': 'Abholen und bezahlen',
};
